[tool.poetry]
name = "jdjgbotsupreme"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
consultor = "^0.2.0"
pytz = "^2020.1"
repl = "^1.0"
flask = "^1.1.2"
dnspython = "^1.16.0"
bs4 = "^0.0.1"
discord-webhook = "^0.8.0"
tweepy = "^3.9.0"
youtube-dl = "^2020.6.16"
aiohttp = "^3.6.2"
async-timeout = "^3.0.1"
discord = "^1.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
