[tool.poetry]
name = "repl_python3_JDJGBotSupreme"
version = "0.1.0"
description = ""
authors = ["repl.it user <replituser@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pytz = "^2020.4"
emojis = "^0.6.0"
flask = "^1.1.2"
giphy-client = "^1.0.0"
bs4 = "^0.0.1"
tweepy = "^3.9.0"
pymongo = "^3.11.0"
bson = "^0.5.10"
discord-webhook = "^0.11.0"
dnspython = "^2.0.0"
google-images-search = "^1.3.4"
termcolor = "^1.1.0"
aiodns = "^2.0.0"
"mystbin.py" = "^0.3.5"
"discord.py" = {extras = ["voice"], version = "^1.5.1"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
