[tool.poetry]
name = "repl_python3_beta_JDJGBotSupreme"
version = "0.1.0"
description = ""
authors = ["repl.it user <replituser@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
flask = "^1.1.2"
bson = "^0.5.10"
discord-webhook = "^0.9.0"
pymongo = "^3.11.0"
async-timeout = "^3.0.1"
bs4 = "^0.0.1"
discord = "^1.0.1"
aiohttp = "^3.6.2"
pytz = "^2020.1"
tweepy = "^3.9.0"
youtube-dl = "^2020.9.20"
dnspython = "^2.0.0"
google-images-search = "^1.3.3"
pil-compat = "^1.0.0"
giphy-client = "^1.0.0"
pastebin = "^1.1.2"
termcolor = "^1.1.0"
wget = "^3.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
